module.exports = {
    alps: require('./alps'),
    button: require('./button'),
    choc: require('./choc'),
    chocmini: require('./chocmini'),
    diode: require('./diode'),
    jstph: require('./jstph'),
    jumper: require('./jumper'),
    mx: require('./mx'),
    oled: require('./oled'),
    omron: require('./omron'),
    pad: require('./pad'),
    promicro: require('./promicro'),
    promicro_pretty: require('./promicro_pretty'),
    nice_nano: require('./nice_nano'),
    nice_view: require('./nice_view'),
    EVQPUC: require('./EVQPUC'),
    rgb: require('./rgb'),
    text: require('./text'),
    rotary: require('./rotary'),
    scrollwheel: require('./scrollwheel'),
    slider: require('./slider'),
    trrs: require('./trrs'),
    via: require('./via'),
    kailhsocket: require('./kailh_socket'),
    mountinghole: require('./mountinghole'),
}